services:
  postgres:
    restart: $RESTART_POLICY
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - $POSTGRES_LISTEN:5432
    volumes:
      - $POSTGRES_DATA:/var/lib/postgresql/data
  redis:
    image: redis:7
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - $REDIS_LISTEN:6379
    volumes:
      - $REDIS_DATA:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
